# Generated by Django 3.2.18 on 2023-03-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleApp', '0005_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default="Pas d'informations", null=True),
        ),
    ]
